### ISSUE TITLE
Would you like to develop libtrusterd under trusterd organization?

### ISSUE THREAD

**Issue by matsumotory** [trusterd/libtrusterd#1]
@kjunichi 
Hi, I'm an author of trusterd.
libtrusterd is a very interesting project and thank you for using mruby-http2! So, the libtrusterd is very close to trusterd project. If you don't mind, would you like to develop libtrusterd under trusterd organization?

**Comment by kjunichi** [comment]
Thank you for your offer.Let me know details.
I don't have enough skill to development with github style,But I'll do my best.

**Comment by matsumotory** [comment]
OK, we'll go through the below procedure. It's very simple procedure.
1. you add me to the collaborator of `kjunichi/libtrusterd`
2. I move `kjunichi/libtrusterd` to `trusterd/libtrusterd`
3. I add you to the collaborator of `trusterd/libtrusterd`

then, you commit to `trusterd/libtrusterd` freely as before.

**Comment by kjunichi** [comment]
I added you to the collaborator of my repository.
Please proceed.

**Comment by matsumotory** [comment]
@kjunichi Ah, sorry. Could you transfer ownership to `trusterd/libtrusterd` from settings yourself? I added you to the collbaborator of libtrusterd team in `trusterd` repository.

**Comment by kjunichi** [comment]
@matsumoto-r 
Thanks for supportting.

I tried to transfer ownership to "trusterd/libtrusterd" from settings.
but Github said that Cannot find new owner 'trusterd/libtrusterd'.
I tried to transfer ownership to "trusterd" from settings.
Then,Github said that you don't hava admin permission.

How should I do?

**Comment by matsumotory** [comment]
@kjunichi Sorry about that. I now updated permission. Could you try again?

**Comment by kjunichi** [comment]
No problem,I transferd to trusterd/libtrusterd at last.

**Comment by matsumotory** [comment]
Thanks!

**Comment by matsumotory** [comment]
Welcome to trusterd!
