### ISSUE TITLE
Support for Go language

### ISSUE THREAD

**Issue by kjunichi** [trusterd/libtrusterd#2]
Go can't functions pointer to other C library.
We need to inform to how to use with go.
(In this time, I'm not sure about go and cgo.)

**Comment by matsumotory** [comment]
:+1:

**Comment by kjunichi** [comment]
Add examples of Go language these commits.
- 1873d7d04453fd014a42ea2adce1ed15c6cbb761
- e6308fbacb9bf6773c94d3cd8d6da08f3a4b7c3c

**Comment by matsumotory** [comment]
:tada:

**Comment by matsumotory** [comment]
@kjunichi ふと思ったのですが、issueベースで開発するのも非常に良いと思いますが、GitHub的な最近の使い方として、
1. 手元でブランチを作る
2. GitHubにブランチをプッシュする
3. 自動でPull-Request作成ボタンが出力される
4. そのブランチでPull-Requestを一旦作る
5. ブランチに対して変更をプッシュしていく
6. 最後開発が終わったらマージする（自動でcloseされる）

というのが、今の @kjunichi さんがやられている作業をより自動化＋見える化できる開発方法のように思いましたので、気が向きましたら是非試してみて頂ければと思います。

サンプルとしては、以下のようなPull-requestです。

https://github.com/trusterd/mruby-http2/pull/20

**Comment by kjunichi** [comment]
アドバイスありがとうございます！
この機会にブランチによる開発やってみます。
